version: '3.2'

services: 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8008:80'
    environment: 
      - PMA_ARBITRARY=1
    networks: 
      - tools-net

networks:
  tools-net:
    external: true