version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: local_mysql_5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456789'
    volumes:
      - ~/Data/mysql:/var/lib/mysql