# Use root/example as user/password credentials
version: '3.1'

services:
  mysql-8:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - ~/Data/mysql-8:/var/lib/mysql